--  SELECT * FROM STUDENTS_MARKS

-- SELECT FULLNAME FROM STUDENTS_MARKS

-- SELECT AV_MARK FROM STUDENTS_MARKS

-- SELECT COUNTRY FROM STUDENTS_MARKS

-- SELECT MIN_MARK FROM STUDENTS_MARKS

-- SELECT MAX_MARK FROM STUDENTS_MARKS
