-- CREATE TABLE STUDENTS_MARKS (
--     ID SERIAL PRIMARY KEY,  
--     FULLNAME VARCHAR(100) NOT NULL, 
--     CITY VARCHAR(50) NOT NULL,
--     COUNTRY VARCHAR(50) NOT NULL,
--     BIRTHDATE DATE,
--     EMAIL VARCHAR(100) NOT NULL,  
--     PHONENUMBER VARCHAR(20),
--     GROUPNAME VARCHAR(10) NOT NULL,  
--     AV_MARK INT CHECK (AV_MARK > 0),
--     MIN_MARK VARCHAR(50) NOT NULL,  
--     MAX_MARK VARCHAR(50) NOT NULL
-- );


INSERT INTO STUDENTS_MARKS(
	FULLNAME,
	CITY,
	COUNTRY,
	BIRTHDATE,
	EMAIL, 
	PHONENUMBER,
	GROUPNAME,
	AV_MARK,
	MIN_MARK,
	MAX_MARK	
)
VALUES
	('JOHN SMITH', 'LONDON', 'UK', '2003-03-02', 'JOHN.SMITH@MAIL.COM', '292830', 'SCIENCE', 9, 'MATH/8', 'SCIENCE/11'),
	('JANE DOE', 'NEW YORK', 'USA', '2001-04-02', 'JANE.DOE@MAIL.COM', '483920', 'LITERATURE', 7, 'HISTORY/9', 'SCIENCE/11'),
    ('MICHAEL JOHNSON', 'LOS ANGELES', 'USA', '2004-04-08', 'MICHAEL.JOHNSON@MAIL.COM', '584739', 'PHYSICS', 10, 'PHYSICS/2', 'SCIENCE/11');